version: '3.8'

services:
  app:
    container_name: tomcat
    build: ./tomcat
    ports:
      - "8080:8080"
    volumes:
      - ./tomcat/webapps:/usr/local/tomcat/webapps
  db:
    container_name: postgresql
    build: ./postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=web_java
      - POSTGRES_USER=bc
      - POSTGRES_PASSWORD=2068686
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgresql/init:/docker-entrypoint-initdb.d
    restart: always

volumes:
  db-data:
